#cloud-config
groups:
  - ansible
users:
  - name: ansible
    primary_group: ansible
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      -  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDI5apZfuaeBVue+UayNADkX2XcsqjYBGEpeN1RwSIGn8pY/JZHIcxh9we3Tj6fbNxmw3u6F2NDoJvq/turiZgDmYqbS8RNI8HqRca0GTXBuPKlkkW9rmdTu2YpGb9zeccnwPqFA5UAh9hCHNuIn8NXzZvyRkS3IgyAMelv6qPB1RmVt5lNdeimmEOrDnGiwuyNVuf0jXdNmugyIsLm7p9iz1a4q0uitVI8RZGecWA/j9bwLs9oUzAIyTePCqL8zYJRGFFAiyM3xfKVPIQMhkFFVDfjzTHzq24WTuwXDalGkYjV3xinvABWqsZtS6lJt57PgpFPqUm+wWmPqSU5GI4cocsPD/OUWCyMn+nA6SqpCNLI95x5BHFIJfrXzm/DtRCcsk67oToXkmns1dFhFeoQ/iaa4bnHbnTVuswpyehnNEl8oDX14oNf/Ms7iR6pBNbfzE4VnKBdS5QixIMzsr+8PFwo7ZDPQaDz+PkEsD7/zaB1tmQCzRuPg7JgytKL8mc= sk@WIN-HLGQAN12ER9
